### ISSUE TITLE
Responsive V4.8 bei Orientierungswechsel gestört

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#36]
Ich stelle fest, dass die UZSU, wenn ich im Hochformat starte und dann auf Querformat drehe, sich nicht auf die Breite des Bildschirms skaliert.

Starte ich im Querformat und wechsle dann auf Hochformat, verhält sich die VISU korrekt.

Bitte prüf das mal bei Dir...
![](http://i.imgur.com/G9gJVNm.jpg)
![](http://i.imgur.com/TO4wo86.jpg)
![](http://i.imgur.com/x6JUvJm.jpg)

**Comment by mworion** [comment]
Sollte so nicht sein. Ich hatte das nur mit dem Safari Browser ausprobiert, der eine Kontrolle bei responsive design ermöglicht. Real an Geräten hatte ich es nicht ausprobiert. Ist u.U. schwierig, da ich explizit im Widget nichts dazu mache. Das sollte alles das JqueryMobile Framework machen.

**Comment by mworion** [comment]
mal Mr. Google gefragt. Da kommt: 
With many sites leveraging jQuery UI, there are some major shortcomings that have to be overcome because jQuery UI does not support responsive design and there's a longstanding bug when maxWidth is used in conjunction with width:'auto'.
Das wird wohl unser Problem sein. Das steckt aber im Framework. Ich habe da ehrlich gesagt keine Idee für einen Workaround, denn die genannten müssten in das Frameweork rein.

**Comment by mworion** [comment]
Closed without action. Kann Ich nachvollziehen auch in der Simulation, habe aber mehrere Versuche ohne erfolg zu einem Redraw gemacht. Ich komme dort nicht weiter.

**Comment by mworion** [comment]
Ich habe es jetzt schwarz auf weiss: Das Drehen bei geöffneten Popup ist kein Auslegungs Use Case im Framework, und wird daher nicht umgesetzt! Siehe Anfrage und Antwort des Maintainers: 

slayergirl commented on Aug 2, 2012
When I switch my phone to landscape (or to potrait) when a popup is opened it's not positioned over the div id I originally put in the data-position-to after the change of orientation.

I think if phone changes orientation the position of the popup should be recalculated so it's still positioned where it's expected.
@toddparker

toddparker commented on Aug 2, 2012
@slayergirl - I agree this would be ideal. We worked on it for a while but this is really complex. When you change orientations, the thing the popup is centered over (if origin or selector is used) will most likely scroll completely out of view. We then had to manually scroll that element back into view, then re-position the popup which was slow, buggy and looked very jumpy. Since popups were designed to be opened for brief amounts of time, we decided to keep it simple and switch to positioning to the window for an open popup once an orientation change occurred.

Closing as won't fix since this is working as designed. We'll update the docs to note this.
